Feature/login
josipzavada/tv-shows-VIPER pull request #1
Opened 2021-09-20 15:06 UTC by josipzavada

- Conform project structure to VIPER
- Add Login VIPER module
- Add login and registration functionality
- Navigate to home when login or registration is successful
- Add empty Home VIPER module

2021-09-21 11:05 UTC, kvaljeva requested changes

2021-09-21 11:05 UTC, kvaljeva commented on TV Shows VIPER/TV Shows VIPER/Modules/Login/LoginViewController.swift
> +        setUpLogInButton()
Love seeing this neatly organised into functions. The only thing I'd personally change is, create a function `setupView` or `setupUI` and move all of these in there to have the lifecycle functions not as cluttered.

2021-09-21 11:05 UTC, kvaljeva commented on TV Shows VIPER/TV Shows VIPER/Modules/Login/LoginViewController.swift
> +            // TODO: Login user
I guess that this is still missing? 😄

2021-09-21 11:05 UTC, kvaljeva commented on TV Shows VIPER/TV Shows VIPER/Modules/Login/LoginWireframe.swift
> +    func start(in window: UIWindow?) {
Left a comment about this as well. Ideally I'd contain it in a class somewhere instead of keeping it on a particular wireframe.

2021-09-21 15:34 UTC, kvaljeva commented on TV Shows VIPER/TV Shows VIPER/Common/Constants.swift
> +        static let didLogOut = Notification.Name("didLogout")
Do you need this notification name?

2021-09-21 15:37 UTC, kvaljeva commented on TV Shows VIPER/TV Shows VIPER/Common/Networking/EndpointItem.swift
> +    var params: [String: String] {
While this is ok, in due time it would result in a rather huge file with all of the parameters for the entire app. Since you're already using codable, you might as well make use of it here. Just make a model for this, say, `LoginRequestModel`, make it `Encodable` and have `JSONEncoder` do the work for you!
You could also move this into an extension over `Codable` to be able to encode models by using something like: `loginRequestModel.toParameters()`

2021-09-22 07:05 UTC, josipzavada commented on TV Shows VIPER/TV Shows VIPER/Modules/Login/LoginPresenter.swift
> +            let email = email,
You are right, but I still need to unwrap email and password. Is it ok if the code looks like this, or can it be improved even more:
`func didSelectRegisterAction(email: String?, password: String?, rememberMe: Bool) {
        guard
            let email = email,
            let password = password,
            Self.areInputsValid(inputs: [email, password])
        else {`

2021-09-22 07:34 UTC, josipzavada commented on TV Shows VIPER/TV Shows VIPER/Common/Constants.swift
> +        static let didLogOut = Notification.Name("didLogout")
I copy-pasted this file from academy homework. I will need it when implementing logout functionality. HomeWireframe will subscribe to it and it will set LoginWireframe as root wireframe to its navigation controller.

2021-09-27 06:19 UTC, kvaljeva approved these changes

2021-09-27 06:47 UTC, merged